print("Data Types: int, float, string")
print("int Examples: 10, 4, 8, 56616")
print("float Examples: 10.0, 3.14, 5.5")
print("String Concatenation example: 'Alice' + 'Bob'")
print('Alice' + 'Bob')
print("String Replication example: 'Alice' * 3 ")
print('Alice' * 3)
print("Other example: 'Hello' + '!' * 10 ")
print('Hello' + '!' * 10)